create extension if not exists pgcrypto;

create schema if not exists extensions;

do $$
begin
  begin
    create extension if not exists pg_cron;
  exception when others then
    raise notice 'pg_cron extension is unavailable in this environment. AI watcher scheduling will need an external cron trigger. %', sqlerrm;
  end;

  begin
    create extension if not exists pg_net with schema extensions;
  exception when others then
    raise notice 'pg_net extension is unavailable in this environment. AI watcher scheduling will need an external cron trigger. %', sqlerrm;
  end;

  begin
    create extension if not exists vault;
  exception when others then
    raise notice 'vault extension is unavailable in this environment. AI watcher scheduling will need an external cron trigger. %', sqlerrm;
  end;
end;
$$;

create table if not exists public.moderation_flags (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('post', 'comment', 'post_reaction', 'comment_reaction', 'profile')),
  entity_id text not null,
  related_post_id uuid null references public.posts(id) on delete set null,
  related_comment_id uuid null references public.post_comments(id) on delete set null,
  related_profile_id uuid null references public.profiles(id) on delete set null,
  actor_user_id uuid null references public.profiles(id) on delete set null,
  content_url text not null,
  excerpt text null,
  reason text not null,
  categories text[] not null default '{}'::text[],
  confidence_score numeric(4, 3) not null check (confidence_score >= 0 and confidence_score <= 1),
  source_created_at timestamptz not null,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open', 'reviewed', 'dismissed')),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz null,
  reviewed_by uuid null references public.profiles(id) on delete set null
);

create unique index if not exists moderation_flags_entity_key
  on public.moderation_flags (entity_type, entity_id);

create index if not exists moderation_flags_status_created_idx
  on public.moderation_flags (status, created_at desc);

create index if not exists moderation_flags_last_seen_idx
  on public.moderation_flags (last_seen_at desc);

create index if not exists moderation_flags_source_created_idx
  on public.moderation_flags (source_created_at desc);

create index if not exists moderation_flags_related_post_idx
  on public.moderation_flags (related_post_id);

create index if not exists moderation_flags_related_comment_idx
  on public.moderation_flags (related_comment_id);

create index if not exists moderation_flags_related_profile_idx
  on public.moderation_flags (related_profile_id);

create table if not exists public.moderation_daily_reports (
  id uuid primary key default gen_random_uuid(),
  report_date date not null unique,
  summary text not null,
  flagged_count integer not null default 0 check (flagged_count >= 0),
  open_flag_count integer not null default 0 check (open_flag_count >= 0),
  category_counts jsonb not null default '{}'::jsonb,
  top_items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists moderation_daily_reports_date_idx
  on public.moderation_daily_reports (report_date desc);

create table if not exists public.moderation_watch_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  completed_at timestamptz null,
  status text not null default 'running' check (status in ('running', 'success', 'error', 'skipped')),
  provider text null,
  model text null,
  scanned_posts integer not null default 0 check (scanned_posts >= 0),
  scanned_comments integer not null default 0 check (scanned_comments >= 0),
  scanned_reactions integer not null default 0 check (scanned_reactions >= 0),
  scanned_profiles integer not null default 0 check (scanned_profiles >= 0),
  flagged_count integer not null default 0 check (flagged_count >= 0),
  error_message text null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists moderation_watch_runs_started_idx
  on public.moderation_watch_runs (started_at desc);

create index if not exists moderation_watch_runs_status_idx
  on public.moderation_watch_runs (status, started_at desc);

comment on table public.moderation_flags is 'AI watcher flags generated by the scheduled moderation bot.';
comment on table public.moderation_daily_reports is 'Daily admin summaries generated by the AI watcher bot.';
comment on table public.moderation_watch_runs is 'Execution history for the AI watcher scheduled job.';

alter table public.moderation_flags enable row level security;
alter table public.moderation_daily_reports enable row level security;
alter table public.moderation_watch_runs enable row level security;

drop policy if exists "Admin can read moderation flags" on public.moderation_flags;
create policy "Admin can read moderation flags"
  on public.moderation_flags for select
  to authenticated
  using (auth.uid() = '794077c7-ad51-47cc-8c25-20171edfb017'::uuid);

drop policy if exists "Admin can update moderation flags" on public.moderation_flags;
create policy "Admin can update moderation flags"
  on public.moderation_flags for update
  to authenticated
  using (auth.uid() = '794077c7-ad51-47cc-8c25-20171edfb017'::uuid)
  with check (auth.uid() = '794077c7-ad51-47cc-8c25-20171edfb017'::uuid);

drop policy if exists "Admin can read moderation daily reports" on public.moderation_daily_reports;
create policy "Admin can read moderation daily reports"
  on public.moderation_daily_reports for select
  to authenticated
  using (auth.uid() = '794077c7-ad51-47cc-8c25-20171edfb017'::uuid);

drop policy if exists "Admin can read moderation watch runs" on public.moderation_watch_runs;
create policy "Admin can read moderation watch runs"
  on public.moderation_watch_runs for select
  to authenticated
  using (auth.uid() = '794077c7-ad51-47cc-8c25-20171edfb017'::uuid);

-- Scheduler prerequisites (run once in SQL if Vault does not already contain them):
-- select vault.create_secret('https://<project-ref>.supabase.co', 'project_url');
-- select vault.create_secret('<strong-random-token>', 'ai_watcher_cron_token');

do $$
declare
  existing_job record;
  project_url text;
  cron_token text;
  has_cron boolean := false;
  has_net boolean := false;
  has_vault boolean := false;
begin
  select exists(select 1 from pg_extension where extname = 'pg_cron') into has_cron;
  select exists(select 1 from pg_extension where extname = 'pg_net') into has_net;
  select exists(select 1 from pg_extension where extname = 'vault') into has_vault;

  if not has_cron or not has_net or not has_vault or to_regclass('cron.job') is null then
    raise notice 'AI watcher cron was not scheduled. pg_cron, pg_net, or vault is unavailable in this environment.';
    return;
  end if;

  for existing_job in select jobid from cron.job where jobname = 'ai-watcher-bot-every-120-minutes' loop
    perform cron.unschedule(existing_job.jobid);
  end loop;

  select decrypted_secret into project_url
  from vault.decrypted_secrets
  where name = 'project_url'
  limit 1;

  select decrypted_secret into cron_token
  from vault.decrypted_secrets
  where name = 'ai_watcher_cron_token'
  limit 1;

  if project_url is null or cron_token is null then
    raise notice 'AI watcher cron was not scheduled. Add Vault secrets named project_url and ai_watcher_cron_token, then rerun the scheduling block.';
  else
    perform cron.schedule(
      'ai-watcher-bot-every-120-minutes',
      '0 */2 * * *',
      format($job$
        select net.http_post(
          url := %L,
          headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'x-ai-watcher-cron-token', %L
          ),
          body := jsonb_build_object(
            'trigger', 'pg_cron',
            'scheduled_at', now()
          )
        ) as request_id;
      $job$, rtrim(project_url, '/') || '/functions/v1/ai-watcher', cron_token)
    );
  end if;
end;
$$;